/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yczhang' at '12/22/16 9:16 PM' with Gradle 2.14.1
 *
 * @author yczhang, @date 12/22/16 9:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
